In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import scale

import math
from scipy import linalg

import ite
from ite.cost.x_kernel import Kernel

In [5]:
# Import data
def load_data():
    full_data = pd.read_csv("X.csv")
    train_y = pd.read_csv("ytr.csv")
    # Rename columns to something more interpretable
    columns = (["reflectance_" + str(i) for i in range(7)]
               + ["solar_" + str(i) for i in range(5)] + ["id"])
    full_data.columns = columns
    
    # Move ID column to the beginning
    id_column = full_data["id"]
    full_data.drop(labels=["id"], axis=1, inplace = True)
    full_data.insert(0, "id", id_column)
    # Add y to the data frame
    split = 98000
    y_id_dict = train_y.set_index("Id")["y"].to_dict()
    full_data.loc[:(split-1), "y"] = full_data.loc[:(split-1), "id"].map(y_id_dict)

    train, test = full_data[:split], full_data[split:]
    return (train, test)

#columns = (["id"] + ["reflectance_" + str(i) for i in range(7)]
 #          + ["solar_" + str(i) for i in range(5)] + ["y"])
#full_data = pd.read_csv("MODIS.csv", header=None, names=columns)
#split = 98000
#train, test = full_data[:split].copy(), full_data[split:].copy()
#train = full_data.copy()

#train_copy, test_copy = load_data()

train, test = load_data()
#full_data = load_data()

# Parameters
n_threads = -1
random_seed = 8888

### Data generation for MATLAB

In [3]:
full_data = full_data.fillna(0)

In [4]:
cols_excl = ["id", "y"]
cols_orig = [c for c in full_data.columns if c not in cols_excl]

# Standardise data for LR
full_data[cols_orig] = scale(full_data[cols_orig])

# I did standardise the data
full_data.to_csv("aerosol_full.csv", encoding="utf-8", index=False, header=False)

### Preprocessing

In [6]:
cols_excl = ["id", "y"]
cols_orig = [c for c in train.columns if c not in cols_excl]

# Standardise data for LR
train[cols_orig] = scale(train[cols_orig])
test[cols_orig] = scale(test[cols_orig])

### Python mean embedding

In [ ]:
def mean_embedding(X1, X2, kernel):
    k = Kernel(kernel)
    gram_mat = k.gram_matrix2(X1, X2)
    # Number of instances in the bag
    N = float(gram_mat.shape[0])
    mu_X1_X2 = gram_mat.ravel().sum() / N**2
    return (mu_X1_X2)

nb_bag = 200#train["id"].nunique()
K_matrix = np.zeros((nb_bag, nb_bag))

theta = 10**(-8)
for i in range(nb_bag):
    for j in range(nb_bag):
        # Compute mean embedding
        X1 = train.loc[train["id"] == (i+1), cols_orig].values
        X2 = train.loc[train["id"] == (j+1), cols_orig].values
        
        K_matrix[i, j] = mean_embedding(X1, X2, {'name': 'invmquadr','c': theta})

y_train = train["y"].unique()[:200].reshape((-1, 1))
l2_reg = 10**(-8)

y_hat = []
test_id_list = np.arange(980, 1100, dtype=int)

for test_id in test_id_list:
    K_test = np.zeros((1, nb_bag))

    for j in range(nb_bag):
        X1 = train.loc[train["id"] == (j+1), cols_orig].values
        X2 = test.loc[test["id"] == test_id, cols_orig].values
        K_test[0, j] = mean_embedding(X1, X2, {'name': 'invmquadr','c': theta})

    # Ridge regression
    ridge_mat = K_matrix + (l2_reg * nb_bag) * np.identity(nb_bag)
    ridge_mat_inv = np.linalg.solve(ridge_mat, np.identity(nb_bag))
    y_hat.append((K_test.dot(ridge_mat_inv)).dot(y_train)[0, 0])

y_hat = np.array(y_hat)

np.sqrt(mean_squared_error(y_hat, test["y"].unique()[:120]))

### Ridge regression

In [85]:
G

0        1        2        3        4        5        6        7     \
0     0.99115  0.95533  0.96953  0.97313  0.90892  0.88619  0.90212  0.97110   
1     0.95533  0.99469  0.96207  0.94358  0.95819  0.88985  0.91499  0.93228   
2     0.96953  0.96207  0.99615  0.96699  0.94579  0.90377  0.92736  0.94237   
3     0.97313  0.94358  0.96699  0.97993  0.89163  0.85203  0.87352  0.97583   
4     0.90892  0.95819  0.94579  0.89163  0.99568  0.93604  0.94812  0.85539   
5     0.88619  0.88985  0.90377  0.85203  0.93604  0.96013  0.93965  0.82410   
6     0.90212  0.91499  0.92736  0.87352  0.94812  0.93965  0.96502  0.83803   
7     0.97110  0.93228  0.94237  0.97583  0.85539  0.82410  0.83803  0.99302   
8     0.90806  0.95982  0.92925  0.88128  0.97786  0.92527  0.95009  0.85219   
9     0.87803  0.88996  0.89890  0.84208  0.94144  0.95463  0.96303  0.80690   
10    0.93291  0.93046  0.94636  0.90226  0.95770  0.96898  0.95915  0.87777   
11    0.98587  0.94616  0.96608  0.97789  0.90271  0.88013  0.88928  0.97650   
12    0.97647  0.93823  0.95435  0.98231  0.87304  0.84389  0.85310  0.99316   
13    0.96225  0.90490  0.91353  0.95155  0.84303  0.84080  0.83096  0.97418   
14    0.95312  0.93063  0.91526  0.95024  0.86361  0.82533  0.81873  0.96999   
15    0.86985  0.90770  0.91123  0.85455  0.97557  0.92726  0.92139  0.81133   
16    0.97369  0.93291  0.96364  0.97413  0.89177  0.85815  0.87155  0.96765   
17    0.95811  0.96923  0.94636  0.96593  0.90384  0.83168  0.85013  0.96932   
18    0.97827  0.94166  0.96461  0.98029  0.89107  0.85757  0.87329  0.97867   
19    0.96379  0.93149  0.95742  0.93732  0.93673  0.93831  0.92915  0.91939   
20    0.81952  0.84210  0.85031  0.78757  0.90618  0.91670  0.93391  0.74725   
21    0.96945  0.92653  0.95423  0.97698  0.86807  0.83293  0.84274  0.98188   
22    0.82964  0.87515  0.85696  0.79647  0.94930  0.94085  0.93560  0.75970   
23    0.90542  0.94622  0.91520  0.87008  0.96874  0.94971  0.94972  0.84808   
24    0.92392  0.95514  0.92708  0.89207  0.96872  0.94890  0.94414  0.87416   
25    0.95614  0.99090  0.95468  0.93716  0.95619  0.90591  0.91964  0.93125   
26    0.93660  0.97768  0.94650  0.91220  0.97892  0.93189  0.94526  0.89156   
27    0.91929  0.94242  0.95912  0.90314  0.96325  0.93621  0.96794  0.86791   
28    0.93469  0.92157  0.90932  0.94937  0.84820  0.77597  0.79733  0.95704   
29    0.98484  0.94461  0.96181  0.97987  0.89363  0.86968  0.87981  0.98265   
...       ...      ...      ...      ...      ...      ...      ...      ...   
1334  0.95505  0.88832  0.89749  0.94346  0.82105  0.81593  0.81222  0.96811   
1335  0.96527  0.90459  0.92686  0.96351  0.85139  0.82977  0.83613  0.97057   
1336  0.96657  0.98782  0.95624  0.95269  0.94539  0.89324  0.90429  0.95047   
1337  0.88783  0.92885  0.92126  0.86395  0.98733  0.95058  0.94435  0.82675   
1338  0.80826  0.83019  0.83609  0.77493  0.89315  0.90721  0.92405  0.73572   
1339  0.84070  0.91583  0.88127  0.81481  0.95804  0.90691  0.93998  0.77858   
1340  0.93484  0.92667  0.91716  0.94771  0.87029  0.79378  0.81678  0.94414   
1341  0.95424  0.94409  0.94525  0.91805  0.93488  0.94854  0.94312  0.90988   
1342  0.96499  0.97114  0.95171  0.96574  0.91433  0.85647  0.86173  0.97092   
1343  0.80161  0.86137  0.84116  0.77212  0.94365  0.91497  0.92790  0.72927   
1344  0.93976  0.95337  0.92376  0.90340  0.94074  0.92652  0.91962  0.89775   
1345  0.91663  0.90172  0.94280  0.90052  0.94707  0.94567  0.92730  0.86499   
1346  0.96639  0.98917  0.95787  0.94960  0.94906  0.89811  0.90965  0.94621   
1347  0.97059  0.94874  0.95274  0.94292  0.92076  0.92668  0.91993  0.94354   
1348  0.90294  0.90929  0.91285  0.86624  0.93754  0.95566  0.95519  0.84191   
1349  0.95389  0.96600  0.98016  0.94118  0.95522  0.92399  0.95179  0.91813   
1350  0.95861  0.94618  0.98235  0.94998  0.94892  0.91354  0.93656  0.91844   
1351  0.96224  0.95483  0.93956  0.96334  0.89139  0.83649  0.84016  0.97337   
1352  0.9

In [155]:
# Import Gram matrices
# Theta=16
G = pd.read_csv("Cauchy_16_prec.csv", header=None)
nb_bag_train = 980

idx_train = nb_bag_train*4/5 - 1
# Number of train bags after setting aside a validation set
L_train = 980*4/5
idx_test = nb_bag_train
G_train = G.loc[:idx_train, :idx_train]
l2_reg = 2**(-23)

In [156]:
ridge_mat = G_train.values + (l2_reg * L_train) * np.identity(L_train)

In [157]:
G_test = G.loc[:idx_train, idx_test:].values

In [158]:
y_train = train.groupby("id")["y"].median().values[:L_train].reshape((1, -1))

In [159]:
y_train.shape

(1, 784)

In [164]:
linalg.inv(ridge_mat)

array([[  8.77981386e+03,  -8.43105769e+01,  -4.49667931e+00, ...,
          1.63981002e+01,   1.37791367e+02,   3.95052640e+01],
       [ -8.43105769e+01,   9.11051133e+03,  -9.61313104e+01, ...,
         -2.21348521e+01,   1.41806517e+01,  -7.88297002e+01],
       [ -4.49667930e+00,  -9.61313104e+01,   9.01539697e+03, ...,
         -6.00859109e+01,   1.40965214e+02,  -5.07456807e+00],
       ..., 
       [  1.63981002e+01,  -2.21348521e+01,  -6.00859108e+01, ...,
          9.49027770e+03,  -4.77472667e+00,   1.89699626e+01],
       [  1.37791367e+02,   1.41806517e+01,   1.40965214e+02, ...,
         -4.77472668e+00,   8.60306626e+03,   3.54231616e+01],
       [  3.95052640e+01,  -7.88297002e+01,  -5.07456807e+00, ...,
          1.89699626e+01,   3.54231616e+01,   9.22094238e+03]])

In [160]:
np.linalg.solve(ridge_mat, G_train)

array([[ 0.17943787,  0.00787967,  0.00042026, ..., -0.00153257,
        -0.01287799, -0.00369217],
       [ 0.00787967,  0.14853085,  0.00898444, ...,  0.00206873,
        -0.00132532,  0.00736743],
       [ 0.00042026,  0.00898444,  0.15742025, ...,  0.00561563,
        -0.01317462,  0.00047427],
       ..., 
       [-0.00153257,  0.00206873,  0.00561563, ...,  0.11303786,
         0.00044625, -0.00177293],
       [-0.01287799, -0.00132532, -0.01317462, ...,  0.00044625,
         0.19595671, -0.00331065],
       [-0.00369217,  0.00736743,  0.00047427, ..., -0.00177293,
        -0.00331065,  0.13820996]])

In [161]:
y_test_hat = y_train.dot(np.linalg.solve(ridge_mat, G_train))

In [165]:
y_test_hat

array([[-3.54210541, -4.36901474, -2.46632853, -3.65516823, -3.79170122,
        -2.97453006, -2.92730329, -4.15556986, -4.03557199, -3.08474442,
        -3.69951016, -3.10463215, -4.52790111, -4.62900411, -4.2879592 ,
        -1.48809922, -3.85707846, -4.22062233, -3.60454135, -2.77681627,
        -1.75014004, -4.76282215, -3.3359833 , -4.08133128, -4.60206254,
        -5.02167471, -3.9092074 , -3.91205609, -4.2955005 , -3.73622675,
        -1.90012078, -2.29649496, -1.94365281, -2.9638622 , -4.07819226,
        -3.02148717, -3.60030072, -4.14731348, -3.66793206, -3.3944616 ,
        -3.61961744, -4.53242571, -4.75616109, -2.81232932, -3.81501037,
        -3.71206542, -4.0626766 , -3.73487709, -2.81794127, -2.86641083,
        -3.97274976, -4.57874299, -3.82278579, -3.28320867, -3.09115922,
        -2.32980467, -3.27538748, -3.95977944, -4.75872728, -2.10110084,
        -4.97803318, -4.39274374, -4.11029919, -4.48169803, -3.67572566,
        -2.61440613, -2.1108654 , -4.24221275, -3.0

In [162]:
def RMSE(y, y_hat):
    out = np.sqrt(mean_squared_error(y, y_hat))
    return (out)

In [163]:
RMSE(y_test_hat.reshape((-1,)), y_train.reshape((-1,)))
#0.55274397545759535

0.55274695545247921

In [16]:
math.log(1.1921e-07 , 2)

-22.99999140202484

*Prediction 9: RMSE-validation: 0.72545.
Optimal theta: 16, lambda: 1.1921e-07 Public LB: 0.67536 base_kp.^[2:4]